# Generated by Django 5.2.7 on 2025-11-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=list, help_text='\n        [\n            {"visualization_id": 1, "x": 0, "y": 0, "w": 6, "h": 4},\n            {"visualization_id": 2, "x": 6, "y": 0, "w": 6, "h": 4}\n        ]\n        ')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dimension_type', models.CharField(choices=[('category', 'Category'), ('indicator_group', 'Indicator Group'), ('period', 'Period'), ('orgunit', 'Organisation Unit')], max_length=50)),
                ('items', models.JSONField(default=list, help_text='[{"id": "male", "name": "Male"}, {"id": "female", "name": "Female"}]')),
                ('field_mapping', models.JSONField(default=dict, help_text='{"survey_field": "gender", "value_mapping": {"M": "male", "F": "female"}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visualization_type', models.CharField(choices=[('pivot_table', 'Pivot Table'), ('column_chart', 'Column Chart'), ('bar_chart', 'Bar Chart'), ('line_chart', 'Line Chart'), ('area_chart', 'Area Chart'), ('pie_chart', 'Pie Chart'), ('gauge', 'Gauge'), ('single_value', 'Single Value'), ('scatter', 'Scatter Plot'), ('radar', 'Radar Chart')], max_length=50)),
                ('dimensions', models.JSONField(default=dict, help_text='\n        {\n            "data": ["indicator_id_1", "indicator_id_2"],  # Data dimension\n            "period": {"type": "relative", "value": "LAST_12_MONTHS"},  # Period dimension\n            "orgUnit": {"type": "project", "value": "project_id"},  # Org unit dimension\n            "disaggregation": ["gender", "age_group"]  # Category dimensions\n        }\n        ')),
                ('filters', models.JSONField(default=dict, help_text='{"region": "North", "status": "Active"}')),
                ('layout', models.JSONField(default=dict, help_text='\n        {\n            "rows": ["period"],\n            "columns": ["data", "disaggregation"],\n            "filters": ["orgUnit"]\n        }\n        ')),
                ('display_options', models.JSONField(default=dict, help_text='\n        {\n            "show_legend": true,\n            "show_values": true,\n            "target_line": true,\n            "trend_line": false,\n            "colors": ["#3b82f6", "#ef4444", "#10b981"]\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('order', models.IntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analytics.dashboard')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.visualization')),
            ],
            options={
                'ordering': ['order', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_visualizations', to=settings.AUTH_USER_MODEL)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.visualization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'visualization')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_cache', to='projects.project')),
                ('visualization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.visualization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='analytics_a_cache_k_0d5319_idx')],
            },
        ),
    ]
