# Generated by Django 5.2.7 on 2025-11-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0003_survey_archived_by_survey_archived_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('indicator_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('outcome', 'Outcome'), ('impact', 'Impact')], max_length=20)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., %, count, ratio)', max_length=100)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('formula', models.TextField(help_text='Formula for calculation (e.g., field1 + field2)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
                ('achieved_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track')], default='on_track', max_length=20)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='indicators.indicator')),
            ],
            options={
                'ordering': ['-set_at'],
                'unique_together': {('indicator', 'period')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('period', models.CharField(help_text='Time period (e.g., Q1 2024, Jan 2024)', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='surveys.survey')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('indicator', 'survey', 'period')},
            },
        ),
    ]
