# Generated by Django 5.2.7 on 2025-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='filter_criteria',
            field=models.JSONField(blank=True, default=dict, help_text="Filter criteria as JSON (e.g., {'region': 'North', 'status': 'Active'})"),
        ),
    ]
