# Generated by Django 5.2.7 on 2025-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('total_records', models.IntegerField(default=0)),
                ('cleaned_records', models.IntegerField(default=0)),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='cleaned_uploads/')),
                ('cleaned', models.BooleanField(default=False)),
                ('cleaned_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_data', models.JSONField(blank=True, null=True)),
                ('cleaned', models.BooleanField(default=False)),
                ('cleaned_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
