# Generated by Django 5.2.7 on 2025-11-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_archived_by_survey_archived_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydata',
            name='sheet_name',
            field=models.CharField(blank=True, help_text='Name of the Excel sheet this data came from', max_length=255, null=True),
        ),
    ]
