# Generated by Django 5.2.7 on 2025-11-14 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('surveys', '0004_surveydata_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project'),
        ),
    ]
