# Generated by Django 5.2.7 on 2025-11-16 18:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='M&E Data Intelligence System', help_text='Application name displayed throughout the system', max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Company or organization name', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG, JPG, or SVG)', null=True, upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])])),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (ICO or PNG)', null=True, upload_to='branding/favicons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])])),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary theme color (hex format, e.g., #3B82F6)', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', help_text='Secondary theme color (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', help_text='Accent color for highlights (hex format)', max_length=7)),
                ('sidebar_color', models.CharField(default='#1F2937', help_text='Sidebar background color (hex format)', max_length=7)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Africa/Nairobi', 'East Africa Time (EAT)'), ('Africa/Lagos', 'West Africa Time (WAT)'), ('Africa/Johannesburg', 'South Africa Time (SAST)'), ('Africa/Cairo', 'Egypt Time (EET)'), ('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('Europe/London', 'Greenwich Mean Time (GMT)'), ('Europe/Paris', 'Central European Time (CET)'), ('Asia/Dubai', 'Gulf Standard Time (GST)'), ('Asia/Kolkata', 'India Standard Time (IST)'), ('Asia/Shanghai', 'China Standard Time (CST)'), ('Asia/Tokyo', 'Japan Standard Time (JST)')], default='UTC', help_text='Default timezone for the system', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('sw', 'Swahili')], default='en', help_text='Default system language', max_length=5)),
                ('date_format', models.CharField(default='YYYY-MM-DD', help_text='Date format (e.g., YYYY-MM-DD, DD/MM/YYYY, MM/DD/YYYY)', max_length=20)),
                ('items_per_page', models.IntegerField(default=10, help_text='Default number of items per page in lists')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable email notifications system-wide')),
                ('enable_data_export', models.BooleanField(default=True, help_text='Allow users to export data')),
                ('max_file_upload_size_mb', models.IntegerField(default=50, help_text='Maximum file upload size in megabytes')),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('footer_text', models.CharField(blank=True, help_text='Custom footer text', max_length=200)),
                ('show_powered_by', models.BooleanField(default=True, help_text='Show "Powered by" text in footer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
